name: wineapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.31+53

environment:
#  sdk: ">=2.17.0-182.1.beta <3.0.0"
  sdk: ">=2.15.0-116.0.dev <3.0.0"
#  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: #^1.0.5
  cron: #^0.5.0 #> service
  geolocator: #^8.2.1
  location: #^4.4.0
  package_info_plus: #^1.4.2
  video_player: ^2.4.4

#  shared_preferences: ^2.0.15
  http: #^0.13.4 #^0.12.0+2        #use with network
  ars_dialog: #^1.0.8
  app_settings: #^4.1.7
  package_info: #^2.0.2

  #  response: #^0.1.1
  email_validator: #^2.0.1  #^1.0.0
  loading_overlay: #^0.3.0
  pin_code_fields: #^7.4.0 #^5.0.1
  carousel_slider: #^4.1.1 #3.0.0 #^2.1.0
  carousel_pro: #^1.0.0
  smooth_page_indicator: #^1.0.0+2 #0.2.1 #^0.2.0
  url_launcher: #^6.1.3 #^5.0.0 #^5.7.10 #5.7.1   '5.4.0'
  sign_in_with_apple: #^4.0.0
  flutter_local_notifications: #^9.6.0 #^2.0.0+1

#  flutter_facebook_login: ^3.0.0 #^3.0.0
#  flutter_facebook_auth: #^4.0.0 #^3.1.1
  firebase_auth: #^3.3.19 #^1.0.1  #^0.20.0
  google_sign_in: #^5.3.3 #^4.5.6
  animator: #^3.2.0 #^2.0.1
  pull_to_refresh: #^2.0.0 #^1.6.1
#  flutter_html: ^2.2.1 #^0.8.2

  #  scrollable_positioned_list:
  webview_flutter: #^3.0.4

  rxdart: ^0.27.3
  connectivity: #^3.0.6
  get:
  cached_network_image: any
  shimmer: #^2.0.0
  flutter_inappwebview: #^5.4.3+7
  flutter_launcher_icons: #^0.9.3
  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_launcher_icons: "^0.8.0"
#  firebase_core: #^1.11.0
  firebase_messaging: #^11.2.5 #^9.0.0
  shared_preferences: ^2.0.15

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/x/wineapp1.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:

    - lib/lang/en.json
    - lib/lang/ar.json
    - assets/images/app_name.png
    - assets/gif1.gif
    - assets/map.png
    - assets/images/logo.png
    - assets/images/allc2.png
    - assets/images/pop_up1.png
    - assets/images/instagram_button.png
    - assets/images/logo2.png
    - assets/images/gmail_button.png
    - assets/images/facebook_button.png
    - assets/images/wain_logo_title.png
    - assets/images/location.png
    - assets/images/icon_down.png
    - assets/images/search.png
    - assets/images/event_and_services_icon.png
    - assets/images/icon_filter_hor.png
    - assets/images/favorite_border.svg
    - assets/images/favorite_filled.svg
    - assets/images/app_name.svg
    - assets/images/drawer/about_us.svg
    - assets/images/drawer/about_us.svg
    - assets/images/drawer/about_us.png
    - assets/images/drawer/contact_us.svg
    - assets/images/drawer/contact_us.png
    - assets/images/drawer/favorite_border.svg
    - assets/images/drawer/favorite_border.png
    - assets/images/drawer/icon_home.svg
    - assets/images/drawer/icon_home.png
    - assets/images/drawer/privacy_policy.svg
    - assets/images/drawer/privacy_policy.png
    - assets/images/drawer/settings.svg
    - assets/images/drawer/settings.png
    - assets/images/drawer/sing_out.svg
    - assets/images/drawer/sing_out.png
    - assets/images/icon_arrow_left.svg
    - assets/images/favorite_border_offer.svg
    - assets/images/favorite_filled_offer.svg
    - assets/images/drawer/controls_small_checkboxes_empty.svg
    - assets/images/drawer/graphics_navbar_toolbar_icons_white_info.svg
    #  - i18n/en.json
    #  - i18n/ar.json
    - assets/images/pathaa.svg
    - assets/images/pathbb.svg
    - assets/images/pathcc.svg
    - assets/images/mail.svg
    - assets/images/mail_button.png
    - assets/images/password_icon.svg
    - assets/images/pop_up.svg
    - assets/images/pop_up.png
    - assets/images/no_image_avilable.png
    - assets/images/all.png
    - assets/images/allc.png
    - assets/images/icon_home.png
    - assets/images/loadimage.gif
    - assets/images/splaenImage1.png
    - assets/images/splaenImagear2.png
    - assets/images/splaenImage.png
    - assets/images/splaenImagear.png
    - assets/x/ic_launcher.png
    - assets/x/wineapp1.png
    - assets/no.jpeg
    - assets/no.png
    - assets/fi.png
    - assets/gif2.gif

  #    FontsFree-Net-SFProText-Regular.ttf

  fonts:
    - family: SFProText
      fonts:
        - asset: fonts/FontsFree-Net-SFProText-Regular.ttf
          weight: 400
          style: normal